[project]
name = "dv-plot"
version = "0.1.0"
description = "Plot daily volatility histograms for F&O stocks"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "matplotlib>=3.10.3",
    "nsepython2>=0.1.0",
    "pandas>=2.2.3",
]
